# Generated by Django 5.2.17 on 2026-08-31 01:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cirurgia', models.CharField(max_length=255)),
                ('data_cirurgia', models.DateField()),
                ('status', models.CharField(choices=[('a_ser_avaliado', 'A ser avaliado'), ('em_acompanhamento', 'Em acompanhamento'), ('alta', 'Alta'), ('arquivado', 'Arquivado')], default='a_ser_avaliado', max_length=20)),
                ('data_alta', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocalAtendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario_tipo', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico')], max_length=10)),
                ('destinatario_id', models.UUIDField()),
                ('tipo', models.CharField(choices=[('lembrete_envio', 'Lembrete de envio'), ('novo_alerta', 'Novo alerta'), ('nova_mensagem', 'Nova mensagem'), ('resposta_medico', 'Resposta do médico')], max_length=20)),
                ('conteudo', models.CharField(max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='VideoEducativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('categoria', models.CharField(choices=[('curativos', 'Curativos'), ('cuidados', 'Cuidados'), ('complicacoes', 'Complicações'), ('outros', 'Outros')], max_length=15)),
                ('url_video', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duracao_segundos', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EtapaAcompanhamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dia_pos_operatorio', models.PositiveIntegerField()),
                ('data_prevista', models.DateField()),
                ('data_liberacao', models.DateField()),
                ('horario_lembrete', models.TimeField(default='08:00')),
                ('status', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado'), ('concluido', 'Concluído')], default='bloqueado', max_length=10)),
                ('data_envio_real', models.DateTimeField(blank=True, null=True)),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='acompanhamento.cirurgia')),
            ],
            options={
                'ordering': ['dia_pos_operatorio'],
            },
        ),
        migrations.CreateModel(
            name='EnvioFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url_foto', models.URLField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='acompanhamento.etapaacompanhamento')),
            ],
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tem_dor', models.BooleanField(default=False)),
                ('intensidade_dor', models.PositiveSmallIntegerField(default=0)),
                ('evolucao_dor', models.CharField(blank=True, choices=[('melhorando', 'Melhorando'), ('piorando', 'Piorando')], max_length=10, null=True)),
                ('ferida_sangrando', models.BooleanField(default=False)),
                ('secrecao_pus', models.BooleanField(default=False)),
                ('inchaco', models.BooleanField(default=False)),
                ('hematoma', models.BooleanField(default=False)),
                ('ponto_solto_ferida_abriu', models.BooleanField(default=False)),
                ('febre_calafrios', models.BooleanField(default=False)),
                ('conseguiu_curativo', models.BooleanField(default=True)),
                ('percepcao_geral', models.CharField(blank=True, choices=[('melhor', 'Melhor'), ('igual', 'Igual'), ('pior', 'Pior')], max_length=10, null=True)),
                ('mensagem_opcional', models.CharField(blank=True, max_length=200)),
                ('respondido_em', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnese', to='acompanhamento.etapaacompanhamento')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('dor_intensa', 'Dor intensa'), ('sangramento', 'Sangramento'), ('febre', 'Febre'), ('deiscencia', 'Deiscência'), ('secrecao', 'Secreção'), ('outro', 'Outro')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('visualizado', 'Visualizado'), ('resolvido', 'Resolvido')], default='pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='acompanhamento.etapaacompanhamento')),
            ],
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='local_atendimento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias', to='acompanhamento.localatendimento'),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_nascimento', models.DateField()),
                ('crm', models.CharField(max_length=20)),
                ('uf_crm', models.CharField(max_length=2)),
                ('tipo_perfil', models.CharField(choices=[('residente', 'Residente'), ('staff', 'Staff')], max_length=10)),
                ('senha_hash', models.CharField(max_length=255)),
                ('foto_perfil_url', models.URLField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('locais_atendimento', models.ManyToManyField(related_name='medicos', to='acompanhamento.localatendimento')),
            ],
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cirurgias', to='acompanhamento.medico'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remetente_tipo', models.CharField(choices=[('paciente', 'Paciente'), ('medico', 'Médico')], max_length=10)),
                ('remetente_id', models.UUIDField()),
                ('conteudo', models.TextField()),
                ('anexo_url', models.URLField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('cirurgia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='acompanhamento.cirurgia')),
            ],
            options={
                'ordering': ['enviado_em'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=200)),
                ('cartao_sus', models.CharField(blank=True, max_length=15, null=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('senha_hash', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('servico_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='acompanhamento.localatendimento')),
            ],
        ),
        migrations.AddField(
            model_name='cirurgia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cirurgias', to='acompanhamento.paciente'),
        ),
    ]
