# Generated by Django 6.1.1 on 2026-09-22 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acompanhamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='localizacao_lesao',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='enviofoto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_cicatrizes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='etapaacompanhamento',
            name='avaliado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etapaacompanhamento',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_avaliadas', to='acompanhamento.medico'),
        ),
        migrations.AddField(
            model_name='etapaacompanhamento',
            name='classificacao_cicatrizacao',
            field=models.CharField(blank=True, choices=[('favoravel', 'Favorável'), ('atencao', 'Requer atenção'), ('complicacao', 'Complicação')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='etapaacompanhamento',
            name='parecer_medico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='anexo_arquivo',
            field=models.FileField(blank=True, null=True, upload_to='chat/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='is_emergencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='termo_aceito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paciente',
            name='termo_aceito_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviofoto',
            name='url_foto',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
